// Shared shapes for the audiobook reader. Audio never travels through the
// sync outbox — these records are device-local by construction, so nothing
// here carries an updatedAt or a tombstone.

// Recorded on every manifest so audio generated by a future second engine can
// never be played back as though this one produced it.
export type EngineId = "piper";

// A voice id is engine-qualified ("kokoro:af_heart") because the two engines
// have overlapping bare names and a chunk key must never collide across them.
export interface Voice {
  id: string;
  engine: EngineId;
  model: string;
  name: string;
  description: string;
}

// Per-call multipliers on the voice's own VITS inference scales. See
// lib/tts/prosody.ts for what each one buys and why they vary per sentence.
export interface Scales {
  // Duration multiplier: above 1 is slower.
  length: number;
  // Sampling noise in the flow — pitch and timbre variation.
  noise: number;
  // Noise in the duration predictor — how evenly phonemes are timed.
  noiseW: number;
}

export interface WordSpan {
  // Offsets into the document-wide normalized text, so a span resolves to a
  // DOM range through the same index that anchors highlights.
  start: number;
  end: number;
}

// One synthesized unit. Sentence-sized: small enough that its measured
// duration bounds the error of intra-chunk word interpolation, large enough
// that the model still produces natural prosody.
export interface Chunk {
  key: string;
  text: string;
  normStart: number;
  normEnd: number;
  words: WordSpan[];
  // The same sentence as the engine hears it: `text` plus whatever punctuation
  // it takes to get the delivery right. Carried rather than recomputed because
  // a manifest adopted from disk has to be able to re-synthesize a chunk
  // without re-walking the article.
  speech: string;
  // `words`, in the same order, as offsets into `speech`. Word timing is
  // measured against the spoken line and reported against the displayed one,
  // so the two coordinate spaces both have to be on hand.
  speechWords: WordSpan[];
  scales: Scales;
  // Silence that follows this chunk, in milliseconds. Derived from document
  // structure, held by the scheduler rather than baked into the audio.
  gapAfter: number;
}

// Timing measured from the generated waveform. Word times are seconds from
// the start of the chunk.
export interface ChunkTiming {
  duration: number;
  wordTimes: number[];
}

// `bytes` is mirrored onto the manifest so the collector can size an
// audiobook without reading a single audio payload back out of IndexedDB.
export interface StoredChunk extends Chunk {
  duration: number | null;
  wordTimes: number[] | null;
  bytes: number | null;
}

// Content-addressed audio: the key is a hash of (text, voice, model), so the
// same sentence is stored once no matter which article it appears in, and a
// trim that removes a paragraph leaves every other chunk warm.
export interface AudioRecord {
  key: string;
  format: "opus" | "pcm";
  data: ArrayBuffer;
  sampleRate: number;
  duration: number;
  bytes: number;
  createdAt: number;
}

export interface Audiobook {
  articleId: string;
  // Hash of the article's normalized text at generation time. A trim or a
  // Restore changes it and the audiobook is rebuilt.
  contentHash: string;
  voiceId: string;
  engine: EngineId;
  model: string;
  chunks: StoredChunk[];
  // Set by an explicit Download. Pinned audiobooks are exempt from eviction:
  // someone who downloaded an article for a flight should still have it that
  // afternoon.
  pinned: boolean;
  createdAt: number;
  lastPlayedAt: number;
}

export type GenerationState =
  | { status: "idle" }
  | { status: "loading-model"; progress: number }
  | { status: "generating"; done: number; total: number }
  | { status: "ready" }
  | { status: "error"; message: string };
